FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY eureka-server/pom.xml ./eureka-server/pom.xml
COPY eureka-server/src ./eureka-server/src
RUN mvn clean package -f eureka-server/pom.xml -DskipTests -B

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/eureka-server/target/*.jar app.jar
EXPOSE 8761
ENTRYPOINT ["java", "-Xmx256m", "-Xms128m", "-jar", "app.jar"]
